import Head from "next/head";

import { Poppins } from "next/font/google";
import styles from "@component/styles/Home.module.css";
import Header from "@component/component/Header";
import { Box, Card, CardMedia, Container } from "@mui/material";
import Indtroduction from "@component/component/introduction";
import { useTheme } from "@mui/material/styles";
import useMediaQuery from "@mui/material/useMediaQuery";
import FeaturesCardList from "@component/component/Features";
import Challenge from "@component/component/Challenge";
import Career from "@component/component/career";
import Image from "next/image";
import "../public/greenarrow.png";
const Poppin = Poppins({ weight: "500", subsets: ["devanagari"] });

export default function Home() {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${Poppin.className}`}>
        {/* section 1 */}
        <Header></Header>

        <Box
          component={"img"}
          sx={{ maxWidth: "100%", width: "100%" }}
          alt="profession"
          src="Line.svg  "
        ></Box>
        <Card>
          <img
            src="/greenarrow.png"
            alt="image description"
            style={{
              width: "100vw",
              height: "1000px",
              position: "absolute",
              objectFit: "contain",
            }}
          ></img>
          <Indtroduction></Indtroduction>
        </Card>
         <FeaturesCardList></FeaturesCardList>
         <Challenge></Challenge>
        <Career></Career>
      </main>
    </>
  );
}
